version: '3.8'
services:
  db_music:
    container_name: db_music
    image: mongo:7.0.3
    command: mongod --port 101
    ports:
      - '101:101'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: db_music

