version: '3.8'
services:
  db_music:
    container_name: db_music
    image: mongo:7.0.3
    command: mongod --port 101
    volumes:
      - ./server-music/__volumes:/data/db
    ports:
      - '101:101'
    environment:
      MONGO_INITDB_DATABASE: db_music
    networks:
      - internal_net

  back_music:
    build:
      dockerfile: server-music/Dockerfile
    container_name: back_music
    ports:
      - "100:100"
    environment:
      - MONGO_URL=mongodb://db_music:101/db_music
    depends_on:
      - db_music
    networks:
      - internal_net

  client-music:
    build:
      dockerfile: client-music/Dockerfile
    container_name: client-music
    ports:
      - "3000:3000"
    depends_on:
      - back_music


networks:
  internal_net:
    driver: bridge