import type {Metadata} from 'next'
import '@gravity-ui/uikit/styles/fonts.css';
import '@gravity-ui/uikit/styles/styles.css';
import './globals.css'
import React, {ReactNode} from "react";
import MainLayout from "@/components/main-layout";
import Player from "@/components/player/player";
import {StoreProvider} from "@/store/store-provider";
import {VStack} from "@/components/stack";


export const metadata: Metadata = {
  title: 'Page Next App',
  description: 'Generated by create next app',
}

export default function Layout({
                                 children,
                               }: {
  children: ReactNode
}) {


  return (
    <html lang="en">
    <body className="g-root g-root_theme_dark">
    <StoreProvider>
      <VStack>
        <MainLayout title={'Музыкальная площадка'}>
          {children}
        </MainLayout>
        <Player/>
      </VStack>

    </StoreProvider>
    </body>
    </html>
  )
}
